server:
  port: 8080

#actuator config
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

#circuit breaker config
resilience4j:
  circuitbreaker:
    instances:
      serviceA: ## this is the name defined for the breaker
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
    circuit-breaker-aspect-order: 1 #sets the priority of this aspect relative to retries
  retry:
    instances:
      serviceA:
        registerHealthIndicator: true
        maxRetryAttempts: 3
        waitDuration: 1s
    retry-aspect-order: 2 #causes retries to happen before circuit breaker